version: '3'
services:
    test1:
        build:
            dockerfile: ./docker/desafio.dockerfile
            context: .
        image: nginx
        container_name: test1
        networks: 
            desafio-network:
              ipv4_address: 10.0.0.1
        
    test2:
        build:
            dockerfile: ./docker/desafio.dockerfile
            context: .
        image: nginx
        container_name: test2
        networks: 
            desafio-network:
              ipv4_address: 10.0.0.2
            
networks: 
    desafio-network:
        driver: bridge
        ipam:
          config:
          - subnet: 10.0.0.0/24
          #gateway: 10.0.0.250 - Só funciona na versão 2 - Preciso ajustar
          